declare let corePlugins: {
  preflight: Function
  container: Function
  accessibility: Function
  pointerEvents: Function
  visibility: Function
  position: Function
  inset: Function
  isolation: Function
  zIndex: Function
  order: Function
  gridColumn: Function
  gridColumnStart: Function
  gridColumnEnd: Function
  gridRow: Function
  gridRowStart: Function
  gridRowEnd: Function
  float: Function
  clear: Function
  margin: Function
  boxSizing: Function
  display: Function
  aspectRatio: Function
  height: Function
  maxHeight: Function
  minHeight: Function
  width: Function
  minWidth: Function
  maxWidth: Function
  flex: Function
  flexShrink: Function
  flexGrow: Function
  flexBasis: Function
  tableLayout: Function
  borderCollapse: Function
  borderSpacing: Function
  transformOrigin: Function
  translate: Function
  rotate: Function
  skew: Function
  scale: Function
  transform: Function
  animation: Function
  cursor: Function
  touchAction: Function
  userSelect: Function
  resize: Function
  scrollSnapType: Function
  scrollSnapAlign: Function
  scrollSnapStop: Function
  scrollMargin: Function
  scrollPadding: Function
  listStylePosition: Function
  listStyleType: Function
  appearance: Function
  columns: Function
  breakBefore: Function
  breakInside: Function
  breakAfter: Function
  gridAutoColumns: Function
  gridAutoFlow: Function
  gridAutoRows: Function
  gridTemplateColumns: Function
  gridTemplateRows: Function
  flexDirection: Function
  flexWrap: Function
  placeContent: Function
  placeItems: Function
  alignContent: Function
  alignItems: Function
  justifyContent: Function
  justifyItems: Function
  gap: Function
  space: Function
  divideWidth: Function
  divideStyle: Function
  divideColor: Function
  divideOpacity: Function
  placeSelf: Function
  alignSelf: Function
  justifySelf: Function
  overflow: Function
  overscrollBehavior: Function
  scrollBehavior: Function
  textOverflow: Function
  whitespace: Function
  wordBreak: Function
  borderRadius: Function
  borderWidth: Function
  borderStyle: Function
  borderColor: Function
  borderOpacity: Function
  backgroundColor: Function
  backgroundOpacity: Function
  backgroundImage: Function
  gradientColorStops: Function
  boxDecorationBreak: Function
  backgroundSize: Function
  backgroundAttachment: Function
  backgroundClip: Function
  backgroundPosition: Function
  backgroundRepeat: Function
  backgroundOrigin: Function
  fill: Function
  stroke: Function
  strokeWidth: Function
  objectFit: Function
  objectPosition: Function
  padding: Function
  textAlign: Function
  textIndent: Function
  verticalAlign: Function
  fontFamily: Function
  fontSize: Function
  fontWeight: Function
  textTransform: Function
  fontStyle: Function
  fontVariantNumeric: Function
  lineHeight: Function
  letterSpacing: Function
  textColor: Function
  textOpacity: Function
  textDecoration: Function
  textDecorationColor: Function
  textDecorationStyle: Function
  textDecorationThickness: Function
  textUnderlineOffset: Function
  fontSmoothing: Function
  placeholderColor: Function
  placeholderOpacity: Function
  caretColor: Function
  accentColor: Function
  opacity: Function
  backgroundBlendMode: Function
  mixBlendMode: Function
  boxShadow: Function
  boxShadowColor: Function
  outlineStyle: Function
  outlineWidth: Function
  outlineOffset: Function
  outlineColor: Function
  ringWidth: Function
  ringColor: Function
  ringOpacity: Function
  ringOffsetWidth: Function
  ringOffsetColor: Function
  blur: Function
  brightness: Function
  contrast: Function
  dropShadow: Function
  grayscale: Function
  hueRotate: Function
  invert: Function
  saturate: Function
  sepia: Function
  filter: Function
  backdropBlur: Function
  backdropBrightness: Function
  backdropContrast: Function
  backdropGrayscale: Function
  backdropHueRotate: Function
  backdropInvert: Function
  backdropOpacity: Function
  backdropSaturate: Function
  backdropSepia: Function
  backdropFilter: Function
  transitionProperty: Function
  transitionDelay: Function
  transitionDuration: Function
  transitionTimingFunction: Function
  willChange: Function
  content: Function
}

export { corePlugins }
